spring.application.name=pdftoolshub

#File Uploading enabling
spring.servlet.multipart.enabled=true

# Maximum-size file allowed
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB
app.temp-dir=${java.io.tmpdir}/pdf-tools-hub